pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
   stage('deploy') {
      steps {
        sh 'npm install'
        sh 'npm run build'
        sh 'kubectl apply -f deployment.yml'
      }
    }
  }
}
